### ISSUE TITLE
Unable to close drawer programmatically

### ISSUE THREAD

**Issue by joesnarky** [salkuadrat/slide_drawer#4]
I am unable to close the drawer programmatically after clicking on a menu item.

MenuItem('Project', icon: Icons.rss_feed, onTap: () { SlideDrawer.of(context)!.toggle();  }),

Null check is failing with message.

Null check operator used on a null value

I've tried adding SliderDrawer in a MaterialApp best I am getting the same issue.

 MaterialApp(      
      home: new SlideDrawer(
.......
   ))

**Comment by salkuadrat** [comment]
Hi joe,

You can use the updated version 1.0.3 to automatically close the drawer when tap on menu item.
By default, every menu item will close the drawer when it's tapped.

But we can disable this auto close by change isCloseDrawerWhenTapped at MenuItem to false.

**Comment by joesnarky** [comment]
Thanks I'll try that. The solution I previously used was to remove the underscore from the State record to make it public.

Then

GlobalKey<SlideDrawerState> _myKeySliderDrawer = GlobalKey();

SlideDrawer(
        key: _myKeySliderDrawer,
        ......
        MenuItem('Public', icon: Icons.rss_feed, onTap: () {  _myKeySliderDrawer.currentState!.toggle(); }
}

**Comment by joesnarky** [comment]
Thanks. 1.0.3 works perfect for me. I'll close this.
