### ISSUE TITLE
 'MenuItem' is imported from both 'platform_menu_bar.dart' and 'package:slide_drawer/src/item.dart'.

### ISSUE THREAD

**Issue by bradintheusa** [salkuadrat/slide_drawer#9]
Anyone else getting

```
 'MenuItem' is imported from both 'platform_menu_bar.dart' and 'package:slide_drawer/src/item.dart'.
```

This seems to be a Flutter 3 breaking change.

**Comment by hicnar** [comment]
Yep, you're correct. Fork it from the original and fix it by renaming the offending class or fork it from my copy where it is already fixed.

**Comment by bradintheusa** [comment]
Thanks
